package com.biosense.app.data.model

import androidx.compose.ui.graphics.Color

// Daily Challenges - Keep users engaged (AI-generated based on previous day data)
data class DailyChallenge(
    val id: String,
    val title: String,
    val description: String,
    val targetValue: Int,
    val currentValue: Int,
    val unit: String,
    val xpReward: Int,
    val emoji: String,
    val completed: Boolean = false,
    val aiGenerated: Boolean = true, // Indicates if challenge was generated by LLM
    val aiReasoning: String = "" // LLM's reasoning based on previous day data
) {
    val progress: Float
        get() = if (targetValue > 0) (currentValue.toFloat() / targetValue).coerceIn(0f, 1f) else 0f
}

// Health Score - Overall wellness indicator
data class HealthScore(
    val overall: Int, // 0-100
    val physical: Int,
    val mental: Int,
    val recovery: Int,
    val consistency: Int
) {
    val rating: HealthRating
        get() = when {
            overall >= 90 -> HealthRating.EXCELLENT
            overall >= 75 -> HealthRating.GREAT
            overall >= 60 -> HealthRating.GOOD
            overall >= 45 -> HealthRating.FAIR
            else -> HealthRating.NEEDS_ATTENTION
        }
}

enum class HealthRating(
    val title: String,
    val message: String,
    val color: Color,
    val emoji: String
) {
    EXCELLENT(
        "Excellent",
        "You're in peak condition! Keep up the amazing work!",
        Color(0xFF4CAF50),
        "🌟"
    ),
    GREAT(
        "Great",
        "You're doing wonderfully! Small improvements will take you further.",
        Color(0xFF8BC34A),
        "💪"
    ),
    GOOD(
        "Good",
        "Solid progress! Focus on consistency to level up.",
        Color(0xFF64B5F6),
        "👍"
    ),
    FAIR(
        "Fair",
        "You're on the right path. Let's boost those numbers!",
        Color(0xFFFFA726),
        "📈"
    ),
    NEEDS_ATTENTION(
        "Needs Attention",
        "Time to prioritize your health. Small steps make big differences.",
        Color(0xFFEF5350),
        "⚠️"
    )
}

// User Progress - Track challenges and streaks
data class UserProgress(
    val currentStreak: Int,
    val longestStreak: Int,
    val totalChallengesCompleted: Int,
    val daysActive: Int
)

// Sample data generators
object GamificationData {
    fun getSampleProgress(): UserProgress {
        return UserProgress(
            currentStreak = 7,
            longestStreak = 14,
            totalChallengesCompleted = 23,
            daysActive = 45
        )
    }

    // Mock LLM-generated challenges based on previous day data
    fun getSampleChallenges(): List<DailyChallenge> {
        return listOf(
            DailyChallenge(
                id = "1",
                title = "The 10K Odyssey",
                description = "Embark on an epic journey to conquer 10,000 steps today",
                targetValue = 10000,
                currentValue = 3200,
                unit = "steps",
                xpReward = 50,
                emoji = "👟",
                aiGenerated = true,
                aiReasoning = "Yesterday you clocked 7,800 steps - solid effort! But here's the thing: your body is capable of so much more. I noticed your movement drops significantly after 2 PM. The science says: a brisk 20-minute walk post-lunch boosts cognitive function by 30% and demolishes that afternoon energy crash. Time to turn those steps into your superpower. Challenge accepted?"
            ),
            DailyChallenge(
                id = "2",
                title = "The Sleep Sanctuary Protocol",
                description = "Unlock elite recovery with 8 hours of premium sleep tonight",
                targetValue = 480, // 8 hours in minutes
                currentValue = 0,
                unit = "minutes",
                xpReward = 60,
                emoji = "😴",
                aiGenerated = true,
                aiReasoning = "Last night's 6.2 hours? That's survival mode, not thriving mode. Your HRV dropped 18% below baseline - your nervous system is waving red flags. Here's what the data shows: 8 hours isn't just sleep, it's your body's repair workshop. Growth hormone peaks, memories consolidate, immune cells multiply. You're literally upgrading yourself overnight. Set your environment: cool room, dark as a cave, screens off 90 minutes before. Your tomorrow-self will be unstoppable."
            ),
            DailyChallenge(
                id = "3",
                title = "Cardiac Calm Initiative",
                description = "Achieve peak heart efficiency - maintain resting rate under 65 bpm",
                targetValue = 65,
                currentValue = 72,
                unit = "bpm",
                xpReward = 40,
                emoji = "❤️",
                aiGenerated = true,
                aiReasoning = "Yesterday's resting heart rate averaged 70 bpm - your heart's working overtime for no reason. Every beat above optimal is wasted energy. The fix? Strategic calm: box breathing (4-4-4-4), stay mega-hydrated (dehydration spikes HR by 10-15 bpm), and cut that caffeine after noon. Elite athletes live in the 40-60 range because their hearts are efficiency machines. Let's train yours to do more with less. Your cardiovascular system will thank you with decades of service."
            )
        )
    }

    fun getSampleHealthScore(): HealthScore {
        return HealthScore(
            overall = 82,
            physical = 85,
            mental = 78,
            recovery = 80,
            consistency = 86
        )
    }
}
