package com.biosense.app.data.model

import androidx.compose.ui.graphics.Color

// Daily Challenges - Keep users engaged (AI-generated based on previous day data)
data class DailyChallenge(
    val id: String,
    val title: String,
    val description: String,
    val targetValue: Int,
    val currentValue: Int,
    val unit: String,
    val xpReward: Int,
    val emoji: String,
    val completed: Boolean = false,
    val aiGenerated: Boolean = true, // Indicates if challenge was generated by LLM
    val aiReasoning: String = "" // LLM's reasoning based on previous day data
) {
    val progress: Float
        get() = if (targetValue > 0) (currentValue.toFloat() / targetValue).coerceIn(0f, 1f) else 0f
}

// Health Score - Overall wellness indicator
data class HealthScore(
    val overall: Int, // 0-100
    val physical: Int,
    val mental: Int,
    val recovery: Int,
    val consistency: Int
) {
    val rating: HealthRating
        get() = when {
            overall >= 90 -> HealthRating.EXCELLENT
            overall >= 75 -> HealthRating.GREAT
            overall >= 60 -> HealthRating.GOOD
            overall >= 45 -> HealthRating.FAIR
            else -> HealthRating.NEEDS_ATTENTION
        }
}

enum class HealthRating(
    val title: String,
    val message: String,
    val color: Color,
    val emoji: String
) {
    EXCELLENT(
        "Excellent",
        "You're in peak condition! Keep up the amazing work!",
        Color(0xFF4CAF50),
        "🌟"
    ),
    GREAT(
        "Great",
        "You're doing wonderfully! Small improvements will take you further.",
        Color(0xFF8BC34A),
        "💪"
    ),
    GOOD(
        "Good",
        "Solid progress! Focus on consistency to level up.",
        Color(0xFF64B5F6),
        "👍"
    ),
    FAIR(
        "Fair",
        "You're on the right path. Let's boost those numbers!",
        Color(0xFFFFA726),
        "📈"
    ),
    NEEDS_ATTENTION(
        "Needs Attention",
        "Time to prioritize your health. Small steps make big differences.",
        Color(0xFFEF5350),
        "⚠️"
    )
}

// User Progress - Track challenges and streaks
data class UserProgress(
    val currentStreak: Int,
    val longestStreak: Int,
    val totalChallengesCompleted: Int,
    val daysActive: Int
)

// Sample data generators
object GamificationData {
    fun getSampleProgress(): UserProgress {
        return UserProgress(
            currentStreak = 7,
            longestStreak = 14,
            totalChallengesCompleted = 23,
            daysActive = 45
        )
    }

    // Mock LLM-generated challenges based on previous day data
    fun getSampleChallenges(): List<DailyChallenge> {
        return listOf(
            DailyChallenge(
                id = "1",
                title = "Boost Your Steps",
                description = "Reach 8,500 steps to beat yesterday's count",
                targetValue = 8500,
                currentValue = 3200,
                unit = "steps",
                xpReward = 50,
                emoji = "👟",
                aiGenerated = true,
                aiReasoning = "Yesterday you walked 7,800 steps. I noticed you were less active in the afternoon. Try adding a 15-minute walk after lunch to reach your goal!"
            ),
            DailyChallenge(
                id = "2",
                title = "Improve Sleep Quality",
                description = "Sleep 7.5 hours tonight for better recovery",
                targetValue = 450, // 7.5 hours in minutes
                currentValue = 0,
                unit = "minutes",
                xpReward = 60,
                emoji = "😴",
                aiGenerated = true,
                aiReasoning = "Your sleep last night was only 6.2 hours, and your HRV was lower than usual. Prioritizing 7.5 hours tonight will help your body recover better."
            ),
            DailyChallenge(
                id = "3",
                title = "Heart Rate Recovery",
                description = "Keep resting heart rate below 68 bpm",
                targetValue = 68,
                currentValue = 72,
                unit = "bpm",
                xpReward = 40,
                emoji = "❤️",
                aiGenerated = true,
                aiReasoning = "Yesterday your average resting heart rate was 70 bpm, slightly elevated. Focus on stress management and hydration to lower it today."
            )
        )
    }

    fun getSampleHealthScore(): HealthScore {
        return HealthScore(
            overall = 82,
            physical = 85,
            mental = 78,
            recovery = 80,
            consistency = 86
        )
    }
}
